use serde::{Deserialize, Serialize};

use crate::certificate_v2::{
    CertificateActionV2, CertificateApprovalAssuranceV2, CertificateApprovalMethodV2,
    CertificateLifecycleActionV2,
};

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
#[allow(clippy::struct_excessive_bools)]
pub struct VerifiedCertificateExecutionAuthorizationV2 {
    pub authorization_id: String,
    pub jti: String,
    pub pa_reservation_id: String,
    pub operation_id: String,
    pub lease_digest_sha256: String,
    pub command_digest_sha256: String,
    pub action: CertificateActionV2,
    pub issuer: String,
    pub audience: String,
    pub signature_key_id: String,
    pub signature_key_version: String,
    pub signature_public_key_spki_sha256: String,
    pub signature_key_purpose: String,
    pub signature_algorithm: String,
    pub trust_revision: u64,
    pub channel: String,
    pub approval_id: Option<String>,
    pub approval_evidence_digest_sha256: Option<String>,
    pub approval_method: Option<CertificateApprovalMethodV2>,
    pub approval_assurance: Option<CertificateApprovalAssuranceV2>,
    pub approval_issued_at_epoch_s: Option<u64>,
    pub approval_expires_at_epoch_s: Option<u64>,
    pub approval_verified_at_epoch_s: Option<u64>,
    pub security_domain: String,
    pub deployment_id: String,
    pub release_id: String,
    pub release_digest_sha256: String,
    pub checkpoint_id: String,
    pub checkpoint_digest_sha256: String,
    pub checkpoint_sequence: u64,
    pub deployment_provenance_ref: String,
    pub policy_id: String,
    pub policy_digest_sha256: String,
    pub decision_id: String,
    pub decision_digest_sha256: String,
    pub grant_id: String,
    pub grant_digest_sha256: String,
    pub pairwise_subject: String,
    pub requester_pairwise_subject: String,
    pub requester_actor: String,
    pub requester_device: String,
    pub requester_profile: String,
    pub requester_proof_key_ref: String,
    pub approver_pairwise_subject: Option<String>,
    pub approver_actor: Option<String>,
    pub approver_device: Option<String>,
    pub approver_profile: Option<String>,
    pub approver_proof_key_ref: Option<String>,
    pub workload: String,
    pub identity_revocation_epoch: u64,
    pub revocation_snapshot_id: String,
    pub revocation_snapshot_digest_sha256: String,
    pub previous_identity_revocation_epoch: u64,
    pub revocation_snapshot_epoch: u64,
    pub revocation_snapshot_verified_at_epoch_s: u64,
    pub authoritative_revocation_snapshot: bool,
    pub service_id: String,
    pub provider: String,
    pub target_resource_id: String,
    pub target_resource_normalizer_id: String,
    pub target_resource_normalizer_version: String,
    pub target_resource_normalization_digest_sha256: String,
    pub target_resource_normalization_verified: bool,
    pub previous_fence: u64,
    pub current_fence: u64,
    pub expected_resource_version: u64,
    pub previous_lifecycle_revocation_epoch: u64,
    pub lifecycle_revocation_epoch: u64,
    pub target_operation_id: Option<String>,
    pub original_action: Option<CertificateLifecycleActionV2>,
    pub lifecycle_reservation_id: Option<String>,
    pub authority_command_digest_sha256: Option<String>,
    pub unknown_evidence_digest_sha256: Option<String>,
    pub locked_previous_fence: Option<u64>,
    pub locked_current_fence: Option<u64>,
    pub locked_previous_lifecycle_revocation_epoch: Option<u64>,
    pub locked_lifecycle_revocation_epoch: Option<u64>,
    pub issued_at_epoch_s: u64,
    pub expires_at_epoch_s: u64,
    pub one_use: bool,
    pub signature_verified: bool,
}
